resources:
- name: ovftool-linux
  type: s3
  source:
    disable_ssl: false
    endpoint: {{S3_ENDPOINT}}
    bucket: {{S3_OVFTOOL_BUCKET}}
    regexp: VMware-ovftool-(.*)-lin.x86_64.bundle
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: bosh-vsphere-stemcell
  type: s3
  source:
    disable_ssl: false
    endpoint: {{S3_ENDPOINT}}
    bucket: {{S3_STEMCELL_OUTPUT_BUCKET}}
    regexp: bosh-stemcell-(.*)-vsphere-esxi-windows2012R2-go_agent.tgz
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: ps-windows-update
  type: s3
  source:
    disable_ssl: false
    endpoint: {{S3_ENDPOINT}}
    bucket: {{S3_WINDOWS_UPDATE_BUCKET}}
    regexp: PSWindowsUpdate_v(.*).zip
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: base-iso
  type: s3
  source:
    disable_ssl: false
    endpoint: {{S3_ENDPOINT}}
    bucket: {{S3_WINDOWS_ISO_BUCKET}}
    regexp: windows-(.*).iso
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: ultradefrag-zip
  type: s3
  source:
    disable_ssl: false
    endpoint: {{S3_ENDPOINT}}
    bucket: {{S3_ULTRADEFRAG_BUCKET}}
    regexp: ultradefrag-portable-(.*).bin.amd64.zip
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}

- name: version
  type: semver
  source:
    bucket: bosh-windows-client-consumable
    key: versions/consumable-version
- name: bosh-windows
  type: s3
  source:
    bucket: bosh-windows-client-consumable
    regexp: bosh-windows-(.*).json
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: stemcell-builder
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-builder.git

jobs:
- name: create-stemcell
  serial: true
  plan:
  - aggregate:
    - get: bosh-windows
      trigger: true
    - get: ci
    - get: ovftool-linux
    - get: stemcell-builder
    - get: version
    - get: ps-windows-update
    - get: base-iso
    - get: ultradefrag-zip

  - task: extract-consumable
    file: ci/tasks/extract-consumable.yml
  - task: create-vsphere-stemcell
    privileged: true
    file: stemcell-builder/tasks/create-vsphere-stemcell.yml
    params:
      OUTPUT_DIR: bosh-windows-stemcell
      ISO_CHECKSUM_TYPE: "md5"
      ISO_CHECKSUM: {{WINDOWS_ISO_CHECKSUM}}
      MEMSIZE: {{GUEST_MEMSIZE}}
      NUMVCPUS: {{GUEST_CPUS}}
      REMOTE_HOST: {{ESXI_REMOTE_ADDRESS}}
      REMOTE_PORT: "22"
      REMOTE_DATASTORE: {{ESXI_DATASTORE}}
      REMOTE_CACHE_DATASTORE: {{ESXI_CACHE_DATASTORE}}
      REMOTE_CACHE_DIRECTORY: "packer-cache"
      REMOTE_USERNAME: {{ESXI_REMOTE_USER}}
      REMOTE_PASSWORD: {{ESXI_REMOTE_PASSWORD}}
      ADMINISTRATOR_PASSWORD: {{WINDOWS_PASSWORD}}
      GUEST_NETWORK_ADDRESS: {{GUEST_NETWORK_ADDRESS}}
      GUEST_NETWORK_MASK: {{GUEST_NETWORK_MASK}}
      GUEST_NETWORK_GATEWAY: {{GUEST_NETWORK_GATEWAY}}
  - put: bosh-vsphere-stemcell
    params:
      file: bosh-windows-stemcell/bosh-stemcell-*-vsphere-esxi-windows2012R2-go_agent.tgz
