resources:
- name: ovftool-linux
  type: s3
  source:
    bucket: {{S3_OVFTOOL_BUCKET}}
    regexp: VMware-ovftool-(.*)-lin.x86_64.bundle
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: version
  type: semver
  source:
    bucket: {{S3_STEMCELL_VERSION_BUCKET}}
    key: versions/bosh-vsphere-stemcell-version
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: bosh-vsphere-stemcell
  type: s3
  source:
    bucket: {{S3_STEMCELL_OUTPUT_BUCKET}}
    regexp: bosh-stemcell-(.*)-vsphere-esxi-windows2012R2-go_agent.tgz
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: bosh-windows
  type: s3
  source:
    bucket: bosh-windows-client-consumable
    regexp: bosh-windows-(.*).json
- name: stemcell-builder
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-builder.git

jobs:
- name: create-stemcell
  serial: true
  plan:
  - aggregate:
    - get: bosh-windows
      trigger: true
    - get: ci
    - get: ovftool-linux
    - get: stemcell-builder
    - get: version
  - task: extract-consumable
    file: ci/tasks/extract-consumable.yml
    tags: [vsphere]
  - put: version
    params:
      bump: minor
  - task: create-vsphere-stemcell
    privileged: true
    file: stemcell-builder/tasks/create-vsphere-stemcell.yml
    tags: [vsphere]
    params:
      OUTPUT_DIR: bosh-windows-stemcell
      ISO_URL: "http://download.microsoft.com/download/6/2/A/62A76ABB-9990-4EFC-A4FE-C7D698DAEB96/9600.16384.WINBLUE_RTM.130821-1623_X64FRE_SERVER_EVAL_EN-US-IRM_SSS_X64FREE_EN-US_DV5.ISO"
      ISO_CHECKSUM_TYPE: "md5"
      ISO_CHECKSUM: "458ff91f8abc21b75cb544744bf92e6a"
      MEMSIZE: {{GUEST_MEMSIZE}}
      NUMVCPUS: {{GUEST_CPUS}}
      REMOTE_HOST: {{ESXI_REMOTE_ADDRESS}}
      REMOTE_PORT: "22"
      REMOTE_DATASTORE: {{ESXI_DATASTORE}}
      REMOTE_CACHE_DATASTORE: {{ESXI_CACHE_DATASTORE}}
      REMOTE_CACHE_DIRECTORY: "packer-cache"
      REMOTE_USERNAME: {{ESXI_REMOTE_USER}}
      REMOTE_PASSWORD: {{ESXI_REMOTE_PASSWORD}}
      ADMINISTRATOR_PASSWORD: {{WINDOWS_PASSWORD}}
      GUEST_NETWORK_ADDRESS: {{GUEST_NETWORK_ADDRESS}}
      GUEST_NETWORK_MASK: {{GUEST_NETWORK_GATEWAY}}
      GUEST_NETWORK_GATEWAY: {{GUEST_NETWORK_MASK}}
  - put: bosh-vsphere-stemcell
    tags: [vsphere]
    params:
      file: bosh-windows-stemcell/bosh-stemcell-*-vsphere-esxi-windows2012R2-go_agent.tgz
