resource_types:
- name: ami-resource
  type: docker-image
  source:
    repository: pivotalgreenhouse/ami-resource
    tag: latest

resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: bosh-agent
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-agent.git
- name: stemcell-builder
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-builder.git
- name: bosh-agent-zip-version
  type: semver
  source:
    bucket: windows-bosh-integration
    key: versions/bosh-agent-version
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: windows-updates-list
  type: s3
  source:
    bucket: windows-updates-list
    regexp: update-list-(.*).txt
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: bosh-windows-shipit-version
  type: semver
  source:
    bucket: bosh-windows-client-consumable
    key: versions/shipit-version
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: bosh-windows-client-consumable
  type: s3
  source:
    bucket: bosh-windows-client-consumable
    regexp: bosh-windows-(.*).json
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: bosh-agent-zip
  type: s3
  source:
    bucket: windows-bosh-integration
    regexp: bosh-windows-integration-v(.*).zip
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: bosh-agent-deps-zip
  type: s3
  source:
    bucket: bosh-windows-dependencies
    regexp: agent-dependencies-v(.*).zip
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: bosh-vsphere-stemcell-version
  type: semver
  source:
    bucket: bosh-windows-stemcells
    key: versions/bosh-vsphere-stemcell-version
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: bosh-vsphere-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: bosh-stemcell-(.*)-vsphere-esxi-windows2012R2-go_agent.tgz
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: ovftool-linux
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: VMware-ovftool-(.*)-lin.x86_64.bundle
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: vsphere-deployment
  type: bosh-deployment
  source:
    target: {{DIRECTOR_IP}}
    username: {{BOSH_USER}}
    password: {{BOSH_PASSWORD}}
    deployment: sample-errand-windows-deployment
    resources:
- name: windows-ami
  type: ami-resource
  source:
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
    region: us-east-1
    search_options:
      filters:
      - {name: "name", values: ["Windows_Server-2012-R2_RTM-English-64Bit-Base*"]}
      - {name: "state", values: ["available"]}
      owners:
      - amazon
- name: bosh-aws-stemcell-version
  type: semver
  source:
    bucket: bosh-windows-stemcells
    key: versions/bosh-aws-stemcell-version
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: bosh-aws-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: light-bosh-stemcell-(.*)-aws-xen-hvm-windows2012R2-go_agent.tgz
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: bosh-windows-acceptance-tests
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/bosh-windows-acceptance-tests.git

jobs:
- name: compile-and-push
  serial: true
  plan:
  - get: bosh-agent
  - put: bosh-agent-zip-version
    params:
      bump: patch
  - task: compile-agent
    privileged: true
    file: bosh-agent/ci/tasks/compile-agent-windows.yml
  - put: bosh-agent-zip
    params:
      file: compiled-agent-zip/bosh-windows-integration-v*.zip

- name: create-vsphere-stemcell
  serial: true
  plan:
  - aggregate:
    - get: bosh-agent
      tags: [vsphere]
      passed: [compile-and-push]
    - get: stemcell-builder
    - get: bosh-agent-deps-zip
      tags: [vsphere]
    - get: bosh-agent-zip
      tags: [vsphere]
      passed: [compile-and-push]
      trigger: true
    - get: ovftool-linux
      tags: [vsphere]
    - put: version
      resource: bosh-vsphere-stemcell-version
      tags: [vsphere]
      params:
        bump: patch
    - get: bosh-windows-acceptance-tests
  - task: agent-sha
    config:
      platform: linux
      image: docker:///concourse/git-resource
      inputs:
      - name: bosh-agent
      outputs:
      - name: bosh-agent-sha
      run:
        path: bash
        args: ["-c","git --git-dir bosh-agent/.git rev-parse HEAD > bosh-agent-sha/sha"]
  - task: create-vsphere-stemcell
    privileged: true
    file: stemcell-builder/tasks/create-vsphere-stemcell.yml
    tags: [vsphere]
    params:
      OUTPUT_DIR: bosh-windows-stemcell
      ISO_URL: "http://download.microsoft.com/download/6/2/A/62A76ABB-9990-4EFC-A4FE-C7D698DAEB96/9600.16384.WINBLUE_RTM.130821-1623_X64FRE_SERVER_EVAL_EN-US-IRM_SSS_X64FREE_EN-US_DV5.ISO"
      ISO_CHECKSUM_TYPE: "md5"
      ISO_CHECKSUM: "458ff91f8abc21b75cb544744bf92e6a"
      MEMSIZE: "8192"
      NUMVCPUS: "6"
      REMOTE_HOST: {{ESXI_REMOTE_ADDRESS}}
      REMOTE_PORT: "22"
      REMOTE_DATASTORE: "578921d3-1b48ca03-9708-02505600004b"
      REMOTE_CACHE_DATASTORE: "578921d3-1b48ca03-9708-02505600004b"
      REMOTE_CACHE_DIRECTORY: "packer-cache"
      REMOTE_USERNAME: {{ESXI_REMOTE_USER}}
      REMOTE_PASSWORD: {{ESXI_REMOTE_PASSWORD}}
      ADMINISTRATOR_PASSWORD: {{WINDOWS_PASSWORD}}
      GUEST_NETWORK_ADDRESS: "10.85.58.10"
      GUEST_NETWORK_MASK: "255.255.255.0"
      GUEST_NETWORK_GATEWAY: "10.85.58.1"
  - task: test-stemcell
    file: bosh-windows-acceptance-tests/concourse.yml
    tags: [vsphere]
    params:
      BOSH_CLIENT_SECRET: {{BOSH_CLIENT_SECRET}}
      BOSH_CLIENT: {{BOSH_CLIENT}}
      DIRECTOR_UUID: 66bf0aa2-6fa3-4551-aae8-dc83fa81c751
      DIRECTOR_IP: 10.87.23.91:25555
      STEMCELL_NAME: bosh-vsphere-esxi-windows-2012R2-go_agent
      STEMCELL_PATH: bosh-windows-stemcell/bosh-stemcell-*-vsphere-esxi-windows2012R2-go_agent.tgz
      BOSH_CA_CERT: {{BOSH_CA_CERT}}
  - put: bosh-vsphere-stemcell
    tags: [vsphere]
    params:
      file: bosh-windows-stemcell/bosh-stemcell-*-vsphere-esxi-windows2012R2-go_agent.tgz
  - put: windows-updates-list
    params:
      file: updates-list/*.txt
- name: create-aws-stemcell
  plan:
  - aggregate:
    - get: ci
    - get: windows-ami
    - get: stemcell-builder
    - get: bosh-agent
      passed: [compile-and-push]
    - put: version
      resource: bosh-aws-stemcell-version
      params:
        bump: patch
    - get: bosh-agent-zip
      passed: [compile-and-push]
      trigger: true
    - get: bosh-agent-deps-zip
    - get: bosh-windows-acceptance-tests
  - task: agent-sha
    config:
      platform: linux
      image: docker:///concourse/git-resource
      inputs:
      - name: bosh-agent
      outputs:
      - name: bosh-agent-sha
      run:
        path: bash
        args: ["-c","git --git-dir bosh-agent/.git rev-parse HEAD > bosh-agent-sha/sha"]
  - task: create-stemcell
    file: stemcell-builder/tasks/create-aws-stemcell.yml
    params:
      OUTPUT_DIR: bosh-windows-stemcell
      AWS_ACCESS_KEY: {{AWS_ACCESS_KEY}}
      AWS_SECRET_KEY: {{AWS_SECRET_KEY}}
      VPC_ID: vpc-3e38385b
      SUBNET_ID: subnet-110fae67
  - task: test-stemcell
    file: bosh-windows-acceptance-tests/concourse.yml
    params:
      BOSH_PASSWORD: {{AWS_BOSH_PASSWORD}}
      BOSH_USER: {{AWS_BOSH_USER}}
      DIRECTOR_IP: 52.1.65.226:25555
      DIRECTOR_UUID: 5c99d18a-8615-4b1f-bb5a-268b798db37a
      STEMCELL_NAME: bosh-aws-xen-hvm-windows-stemcell-go_agent
      STEMCELL_PATH: bosh-windows-stemcell/light-bosh-stemcell-*-aws-xen-hvm-windows2012R2-go_agent.tgz
  - put: bosh-aws-stemcell
    params:
      file: bosh-windows-stemcell/light-bosh-stemcell-*-aws-xen-hvm-windows2012R2-go_agent.tgz
- name: shipit
  plan:
  - aggregate:
    - get: ci
    - get: bosh-agent
      passed: [create-vsphere-stemcell]
    - get: bosh-agent-zip
      passed: [create-vsphere-stemcell]
    - get: bosh-agent-deps-zip
      passed: [create-vsphere-stemcell]
    - get: windows-updates-list
      passed: [create-vsphere-stemcell]
    - get: bosh-windows-shipit-version
  - put: bosh-windows-shipit-version
    params:
      bump: minor
  - task: create-consumable
    file: ci/tasks/create-consumable.yml
  - put: bosh-windows-client-consumable
    params:
      file: bosh-windows-client-consumable/bosh-windows-*.json
