resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: greenhouse-private
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-cf/greenhouse-private
    private_key: {{GREENHOUSE_PRIVATE_KEY}}
- name: garden-windows-release
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-cf-experimental/garden-windows-bosh-release
    private_key: {{GARDEN_WINDOWS_RELEASE_PRIVATE_KEY}}

- name: diego-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/diego-release

- name: wats
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/wats.git

- name: stonetalon-deploy
  type: bosh-deployment
  source:
    target: {{WATS_BOSH_TARGET_URL}}
    client_id: {{WATS_BOSH_CLIENT_ID}}
    client_secret: {{WATS_BOSH_CLIENT_SECRET}}
    ca_cert: {{WATS_BOSH_TARGET_CERT}}
    deployment: garden-windows
    ignore_ssl: true

- name: bosh-vsphere-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: bosh-stemcell-(.*)-vsphere-esxi-windows2012R2-go_agent.tgz
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}

- name: garden-windows-bosh-release-dev
  type: s3
  source:
    bucket: garden-windows-dev-bosh-release
    regexp: garden-windows-(.*).tgz
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}

- name: garden-windows-bosh-release-final
  type: s3
  source:
    bucket: garden-windows-bosh-release
    regexp: garden-windows-(.*).tgz
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}

- name: version
  type: semver
  source:
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
    bucket: garden-windows-bosh-release-versions
    initial_version: 0.0.0
    key: current-version
    region_name: us-east-1

- name: github-release
  type: github-release
  source:
    user: cloudfoundry-incubator
    repository: garden-windows-bosh-release
    drafts: true
    access_token: {{GREENHOUSE_CI_ACCESS_TOKEN}}

jobs:
- name: patch-bump
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: patch}
  - put: version
    params: {file: version/number}

- name: minor-bump
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor}
  - put: version
    params: {file: version/number}

- name: major-bump
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major}
  - put: version
    params: {file: version/number}

- name: deploy-and-wats
  serial: true
  plan:
  - aggregate:
    - get: release
      resource: garden-windows-release
      trigger: true
      tags: [vsphere]
    - get: greenhouse-private
      tags: [vsphere]
    - get: diego-release
      tags: [vsphere]
      trigger: true
    - get: bosh-vsphere-stemcell
      tags: [vsphere]
      trigger: true
    - get: ci
      tags: [vsphere]
    - get: wats
      tags: [vsphere]
    - get: version
      params: {pre: rc}
  - put: version
    params: {pre: rc}
  - task: create-release
    privileged: true
    file: ci/tasks/bosh-create-release.yml
    tags: [vsphere]
  - put: stonetalon-deploy
    tags: [vsphere]
    params:
      manifest: greenhouse-private/bosh-windows-manifests/garden-windows-stonetalon.yml
      releases: [garden-windows-output/*.tgz, diego-release/*.tgz]
      stemcells: [bosh-vsphere-stemcell/*.tgz]
  - task: wats
    privileged: true
    file: ci/tasks/run-wats.yml
    tags: [vsphere]
    params:
      ADMIN_PASSWORD: {{WATS_CF_PASSWORD}}
      ADMIN_USER: {{WATS_CF_USER}}
      API: {{WATS_CF_API}}
      APPS_DOMAIN: {{WATS_CF_DOMAIN}}
      DOPPLER_URL: {{WATS_DOPPLER_URL}}
      NUM_WIN_CELLS: "2"
      SOCKET_ADDRESS_FOR_SECURITY_GROUP_TEST: {{WATS_BOSH_DIRECTOR_IP}}
  - put: garden-windows-bosh-release-dev
    params:
      file: garden-windows-output/garden-windows-*.tgz

- name: shipit
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: greenhouse-private
    - get: version
      params: {bump: final}
    - get: garden-windows-release
      passed: [deploy-and-wats]
    - get: garden-windows-bosh-release-dev
      passed: [deploy-and-wats]
  - put: version
    params: {file: version/number}
  - task: finalize-release
    file: ci/tasks/finalize_release.yml
  - put: garden-windows-bosh-release-final
    params:
      file: finalized-release/garden-windows-*.tgz
  - put: garden-windows-release
    params:
      repository: finalized-release/garden-windows-release
      tag: version/number
      tag_prefix: v
      rebase: true
  - task: generate-release
    file: ci/tasks/generate_github_release.yml
  - put: github-release
    params:
      commitish: generated-release/commitish
      name: generated-release/name
      tag: generated-release/version
      globs:
      - finalized-release/garden-windows-*.tgz
