---
resources:
- name: ci
  type: git
  source:
    branch: windows-syslog
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: version
  type: semver
  source:
    bucket: bosh-windows-dependencies
    key: version/number
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: bosh-blobstore-dav
  type: s3
  source:
    bucket: davcli
    regexp: davcli-(.*)-windows-amd64.exe
- name: bosh-blobstore-s3
  type: s3
  source:
    bucket: s3cli-artifacts
    regexp: s3cli-(.*)-windows-amd64.exe
- name: tar
  type: s3
  source:
    bucket: bosh-windows-dependencies
    regexp: tar-(.*).exe
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: zlib1
  type: s3
  source:
    bucket: bosh-windows-dependencies
    regexp: zlib1-(.*).dll
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: bosh-agent-deps-zip
  type: s3
  source:
    bucket: bosh-windows-dependencies
    regexp: agent-dependencies-v(.*).zip
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: winsw2
  type: git
  source:
    branch: master
    uri: https://github.com/kohsuke/winsw.git
    tag_filter: winsw-*
# - name: winsw-version
#   type: semver
#   source:
#     bucket: bosh-windows-winsw
#     key: version/number
#     access_key_id: {{AWS_ACCESS_KEY}}
#     secret_access_key: {{AWS_SECRET_KEY}}
- name: winsw-exe
  type: s3
  source:
    bucket: bosh-windows-winsw
    regexp: winsw-(.*).exe
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: winsw-pipe-version
  type: semver
  source:
    bucket: winsw-pipe
    key: version/number
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}
- name: winsw-pipe
  type: git
  source:
    branch: windows-syslog
    uri: https://github.com/cloudfoundry/bosh-agent
    paths:
    - jobsupervisor/pipe
- name: winsw-pipe-exe
  type: s3
  source:
    bucket: winsw-pipe
    regexp: winsw-pipe-(.*).exe
    access_key_id: {{AWS_ACCESS_KEY}}
    secret_access_key: {{AWS_SECRET_KEY}}

jobs:
- name: build-winsw
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: winsw2
      trigger: true
    # - put: version
    #   resource: winsw-version
    #   params: { bump: minor }
  - task: build-winsw
    file: ci/tasks/build-winsw.yml
  - put: winsw-exe
    params: { file: winsw-output/winsw-*.exe }
- name: build-winsw-pipe
  serial: true
  plan:
  - aggregate:
    - get: ci
    - put: version
      resource: winsw-pipe-version
      params: { bump: minor }
    - get: winsw-pipe
  - task: build-winsw-pipe
    file: ci/tasks/build-winsw-pipe.yml
  - put: winsw-pipe-exe
    params: { file: winsw-pipe-output/winsw-pipe-*.exe }
- name: collect-and-zip
  serial: true
  plan:
  - aggregate:
    - get: ci
    - put: version
      params:
        bump: major
    - get: bosh-blobstore-dav
    - get: bosh-blobstore-s3
    - get: winsw-exe
      passed: [build-winsw]
    - get: winsw-pipe-exe
      passed: [build-winsw-pipe]
    - get: tar
    - get: zlib1
  - task: collect-and-zip
    file: ci/tasks/collect-and-zip-agent-deps.yml
  - put: bosh-agent-deps-zip
    params:
      file: bosh-agent-deps-zip/agent-dependencies-v*.zip
