---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ruby } }
inputs:
  - name: greenhouse-private
  - name: ci
run:
  path: ci/scripts/bosh-windows-deploy.sh
params:
  BOSH_TARGET_CERT:
  BOSH_TARGET_NAME:
  BOSH_TARGET_URL:
  BOSH_USER:
  BOSH_PASSWORD:
