---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ruby } }
inputs:
  - name: release
  - name: ci
  - name: version

outputs:
 - name: garden-windows-output

run:
  path: ci/scripts/bosh-create-release.sh
