---
platform: windows

inputs:
- name: version
- name: winsw-pipe
  path: gopath/src/github.com/cloudfoundry/bosh-agent
- name: ci

outputs:
- name: winsw-pipe-output

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/scripts/build-winsw-pipe.ps1
