---
platform: windows

inputs:
- name: winsw2
- name: version
- name: ci

outputs:
- name: winsw-output

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/scripts/build-winsw.ps1
