---
platform: linux
image: docker:///pivotalgreenhouse/ruby
inputs:
  - name: greenhouse-private
run:
  path: greenhouse-ci/scripts/change-cf-admin-password
params:
  BOSH_USER:
  BOSH_PASSWORD:
  BOSH_DIRECTOR_IP:
  OPSMANAGER_VM_USER:
  OPSMANAGER_VM_IP:
  CF_PASSWORD:
