---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ruby } }
inputs:
  - name: greenhouse-private
  - name: greenhouse-ci
run:
  path: greenhouse-ci/scripts/change-cf-admin-password
params:
  BOSH_USER:
  BOSH_PASSWORD:
  BOSH_DIRECTOR_IP:
  OPSMANAGER_VM_USER:
  OPSMANAGER_VM_IP:
  CF_PASSWORD:
