---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci}}

inputs:
  - name: diego-release
  - name: diego-windows-release
  - name: diego-windows-github-release
  - name: greenhouse-ci

run:
  path: greenhouse-ci/scripts/check_templates.rb
