---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/bosh-cli}}
run:
path: bosh
args:
  - -n
  - clean-up
  - --all
params:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
