---
platform: linux
image_resource: {type: docker-image, source: {repository: ruby } }
inputs:
  - name: ci
run:
  path: bash
  args:
    - -c
    - "gem install net-ssh && ./ci/scripts/cleanup-vsphere.rb"
params:
  REMOTE_HOST:
  REMOTE_USERNAME:
  REMOTE_PASSWORD:
  REMOTE_DATASTORE:
