---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/ci

inputs:
- name: ci
- name: windows-ami-us-east-1
- name: windows-ami-us-east-2
- name: windows-ami-us-west-1
- name: windows-ami-us-west-2
# - name: windows-ami-ca-central-1
- name: windows-ami-ap-south-1
- name: windows-ami-ap-northeast-2
- name: windows-ami-ap-southeast-1
- name: windows-ami-ap-southeast-2
- name: windows-ami-ap-northeast-1
- name: windows-ami-eu-central-1
- name: windows-ami-eu-west-1
- name: windows-ami-eu-west-2
- name: windows-ami-sa-east-1

outputs:
- name: stemcell-regions

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

run:
  path: ci/scripts/collect-stemcell-region-amis.rb
