---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/ci

inputs:
- name: ci

outputs:
- name: stemcell-regions

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

run:
  path: ci/scripts/collect-stemcell-region-amis.rb
