---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/ci

inputs:
- name: ci
- name: windows-ami-eu-west-1
- name: windows-ami-us-east-1
- name: windows-ami-us-west-2

outputs:
- name: stemcell-regions

run:
  path: ci/scripts/collect-stemcell-region-amis.rb
