---
platform: linux
image: docker:///pivotalgreenhouse/ruby
inputs:
  - name: diego-windows-msi
  - name: msi-file
  - name: diego-release
  - name: cf-release
  - name: cf-diego-dwm-locker
  - name: greenhouse-ci
run:
  path: greenhouse-ci/scripts/commit-shas-to-git.sh
params:
  KEY:
