platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci } }
inputs:
- name: ci
- name: bosh-agent
outputs:
- name: compiled-agent
run:
  path: ci/scripts/compile-bosh-agent.sh

