---
platform: linux
image: docker:///pivotalgreenhouse/ruby
inputs:
  - name: diego-windows-release
  - name: diego-windows-artifacts
  - name: garden-windows-msi-file
  - name: garden-windows-setup-file
  - name: greenhouse-ci
run:
  path: greenhouse-ci/scripts/release.rb
params:
  GITHUB_TOKEN:

