---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ruby } }
inputs:
  - name: diego-windows-release
  - name: garden-windows-msi-file
  - name: garden-windows-setup-file
  - name: greenhouse-ci
  - name: diego-windows-msi-file
  - name: diego-windows-cloudformation-template-file
  - name: greenhouse-install-script-generator-file
  - name: hakim
run:
  path: greenhouse-ci/scripts/release.rb
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  GITHUB_TOKEN:

