---
platform: linux
image: docker:///pivotalgreenhouse/ruby
inputs:
  - name: garden-windows-bosh-release
  - name: greenhouse-ci
  - name: version
run:
  path: greenhouse-ci/scripts/create-garden-windows-dev-release.sh
outputs:
  - name: garden-windows-bosh-release-tarball
