---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ruby } }
inputs:
  - name: garden-windows-bosh-release
  - name: greenhouse-ci
  - name: version
run:
  path: greenhouse-ci/scripts/create-garden-windows-dev-release.sh
outputs:
  - name: garden-windows-bosh-release-tarball
