---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ruby } }
inputs:
  - name: ci
  - name: bosh-agent
  - name: bosh-agent-zip
  - name: bosh-agent-deps-zip
  - name: windows-updates-list
  - name: bosh-windows-shipit-version
outputs:
  -  name: bosh-windows-client-consumable
run:
  path: ci/scripts/create-consumable.rb

