---
platform: linux

image: docker:///cloudfoundry/diego-pipeline

params:
  BOSH_TARGET: ~
  BOSH_USER: ~
  BOSH_PASSWORD: ~
  DEPLOYMENT_NAME: ~

run:
  path: bash
  args:
  - -c
  - "bosh"
  - -t
  - "${BOSH_TARGET}"
  - delete
  - deployment
  - "${DEPLOYMENT_NAME}"
