---
platform: linux

image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci }}

inputs:
  - name: ci

run:
  path: ci/scripts/delete-vms.rb

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
