---
platform: linux
image: docker:///pivotalgreenhouse/ruby
inputs:
  - name: diego-windows-msi-file
  - name: garden-windows-msi-file
  - name: diego-windows-cloudformation-template-file
  - name: garden-windows-setup-file
  - name: greenhouse-install-script-generator-file
  - name: greenhouse-ci
  - name: diego-windows-release # cloudformation template only
run:
  path: greenhouse-ci/scripts/deploy_msi.rb
  args: [msi-file]
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  BOSH_PASSWORD:
  BOSH_USER:
  CELL_NAME:
  CONTAINERIZER_PASSWORD:
  SUBNET:
  SECURITY_GROUP:
  STACKNAME:
  BOSH_HOST:
