---
platform: linux

image: docker:///cloudfoundry/diego-pipeline

inputs:
  - name: garden-windows-release
  - name: garden-windows-bosh-release-dev
  - name: greenhouse-private
  - name: ci
  - name: version

outputs:
  - name: finalized-release

run:
  path: ci/scripts/finalize_release
