---
platform: linux
image_resource: {type: docker-image, source: {repository: cloudfoundry/diego-pipeline } }
inputs:
  - name: release-develop
  - name: bucket-develop
  - name: greenhouse-private
  - name: ci
  - name: version

outputs:
  - name: finalized-release

run:
  path: ci/scripts/finalize-release
