---
platform: linux
image_resource: {type: docker-image, source: {repository: cloudfoundry/diego-pipeline } }
inputs:
  - name: cf-release
  - name: diego-github-release
  - name: greenhouse-ci
  - name: greenhouse-private
run:
  path: greenhouse-ci/scripts/generate-manifest.sh
outputs:
- name: generate-manifest
