---
platform: linux
image: docker:///cloudfoundry/diego-pipeline
inputs:
  - name: cf-release
  - name: diego-release
  - name: greenhouse-ci
  - name: greenhouse-private
run:
  path: greenhouse-ci/scripts/generate-manifest.sh
