---
platform: linux
image: docker:///pivotalgreenhouse/ruby
inputs:
  - name: diego-windows-msi
  - name: greenhouse-ci
run:
  path: greenhouse-ci/scripts/longrunning-test.sh
params:
  CF_USERNAME:
  CF_PASSWORD:
  MACHINE_IP:
  JUMP_MACHINE_IP:
  JUMP_MACHINE_SSH_KEY: