---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ruby } }
inputs:
  - name: wats
  - name: greenhouse-ci
run:
  path: greenhouse-ci/scripts/longrunning-test.sh
params:
  CF_USERNAME:
  CF_PASSWORD:
  MACHINE_IP:
  SSH_KEY:
  TARGET_URL:
