---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci } }
inputs:
  - name: wats
  - name: greenhouse-ci
  - name: greenhouse-private
run:
  path: greenhouse-ci/scripts/longrunning-test.sh
params:
  CF_USERNAME:
  CF_PASSWORD:
  MACHINE_IP:
