platform: linux
image_resource: {type: docker-image, source: {repository: cloudfoundry/diego-pipeline } }
inputs:
  - name: to-repo
  - name: from-repo
  - name: ci

outputs:
  - name: merged-repo

run:
  path: ci/scripts/merge-repo

params:
  FROM_BRANCH: ~
