---
platform: linux
image: docker:///golang#1.5
inputs:
  - name: wats
run:
  path: wats/scripts/run_wats.sh
params:
  ADMIN_PASSWORD:
  ADMIN_USER:
  API:
  APPS_DOMAIN:
  DOPPLER_URL:
  SOCKET_ADDRESS_FOR_SECURITY_GROUP_TEST:
