---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci } }
inputs:
  - name: ci
  - name: version
  - name: bosh-windows-stemcell
outputs:
  - name: final-stemcell
run:
  path: ci/scripts/set-stemcell-version.rb
