---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ci } }
inputs:
  - name: version
outputs:
  - name: final-version
run:
  path: ruby
  args:
    - "-e"
    - |
      short_version = File.read('version/number').match(/\d+\.\d+/)[0]
      File.write('final-version/number', short_version)
