---
platform: linux
image_resource: {type: docker-image, source: {repository: ruby } }
inputs:
  - name: downstream-release
  - name: upstream-release
  - name: ci
run:
  path: ci/scripts/sync-submodules.rb
outputs:
- name: bumped-downstream-release
