---
platform: linux
image: docker:///pivotalgreenhouse/ruby
inputs:
  - name: garden-windows-bosh-artifacts
  - name: release
  - name: ci
outputs:
  - name: release-output
run:
  path: ci/scripts/update-garden-windows-blobs.sh
