---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/ruby } }
inputs:
  - name: garden-windows-bosh-artifacts
  - name: release
  - name: ci
outputs:
  - name: release-output
run:
  path: ci/scripts/update-garden-windows-blobs.sh
