---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/bosh-cli}}
inputs:
- name: linux-stemcell
run:
  path: bosh
  args:
    - -n
    - upload-stemcell
    - linux-stemcell/stemcell.tgz
