---
platform: linux
image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/bosh-cli}}
inputs:
- name: stemcell
run:
  path: bash
  args:
    - -c
    - bosh
    - -n
    - upload-stemcell
    - stemcell/*.tgz
