---
name: garden-windows
director_uuid: da12b3a5-a060-427c-a60c-9fd0c7643a3c

releases:
- name: garden-windows
  version: latest

networks:
- name: default
  subnets:
  - range: 10.87.23.0/24
    gateway: 10.87.23.1
    reserved: [10.87.23.1, 10.87.23.2, 10.87.23.3, 10.87.23.4]
    dns: [10.87.23.1]
    cloud_properties:
      name: "stonetalon"

resource_pools:
- name: default
  stemcell:
    name: bosh-vsphere-esxi-windows-2012R2-go_agent
    version: latest
  network: default
  cloud_properties:
    cpu: 2
    ram: 2_048
    disk: 2_048

compilation:
  workers: 1
  network: default
  resource_pool: default
  cloud_properties:
    cpu: 2
    ram: 2_048
    disk: 2_048

update:
  canaries: 0
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

jobs:
- name: garden-windows
  templates:
  - name: garden-windows
  instances: 1
  resource_pool: default
  networks:
  - name: default
  properties: {}
