resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: stemcells-major-version
  type: semver
  source:
    bucket: bosh-windows-stemcells
    key: versions/stemcells-major-version-edge
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
    initial_version: 1007.0.0
- name: bosh-agent
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-agent.git
- name: stemcell-builder
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-builder.git
- name: windows-stemcell-dependencies
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-cf/windows-stemcell-dependencies.git
    private_key: {{PIVOTAL-CF_WINDOWS-STEMCELL-DEPENDENCIES_PRIVATE_KEY}}
- name: base-iso
  type: s3
  source:
    bucket: windows-bosh-private
    regexp: en_windows_server_2012_r2_x64_dvd_(.*).iso
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: major-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: stemcell-(.*).json
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: updated-vmx-version
  type: semver
  source:
    bucket: bosh-windows-stemcells
    key: versions/updated-vmx-version
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
    initial_version: "1.0.0"
- name: vsphere-stemcell-version
  type: semver
  source:
    bucket: bosh-windows-stemcells
    key: versions/vsphere-stemcell-version-edge
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
    initial_version: 1000.0.0
- name: vsphere-stemcell-pre-release-candidate
  type: s3
  source:
    bucket: bosh-windows-stemcells-pre-release-candidate
    regexp: bosh-stemcell-(.*)-vsphere-esxi-windows2012R2-go_agent.tgz
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: vsphere-stemcell-release-candidate
  type: s3
  source:
    bucket: bosh-windows-stemcells-private-release-candidates
    regexp: bosh-stemcell-(.*)-vsphere-esxi-windows2012R2-go_agent.tgz
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: vsphere-stemcell-final
  type: s3
  source:
   bucket: bosh-windows-stemcells-private
   regexp: bosh-stemcell-(.*)-vsphere-esxi-windows2012R2-go_agent.tgz
   access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
   secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: aws-lock
  type: pool
  source:
    branch: master
    pool: stemcells-aws
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks
- name: aws-stemcell-version
  type: semver
  source:
    bucket: bosh-windows-stemcells
    key: versions/aws-stemcell-version-edge
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
    initial_version: 1000.0.0
- name: aws-stemcell-sha
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: light-bosh-stemcell-(.*)-aws-xen-hvm-windows2012R2-go_agent.tgz.sha
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: aws-stemcell-release-candidate
  type: s3
  source:
    bucket: bosh-windows-stemcells-release-candidates
    regexp: light-bosh-stemcell-(.*)-aws-xen-hvm-windows2012R2-go_agent.tgz
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: aws-stemcell-final
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: light-bosh-stemcell-(.*)-aws-xen-hvm-windows2012R2-go_agent.tgz
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: base-amis-win2012r2
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: base-amis-windows2012R2-(.*).json
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: base-gcp-image-win2012r2
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: base-gcp-image-windows2012R2-(.*).json
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: gcp-lock
  type: pool
  source:
    branch: master
    pool: stemcells-gcp
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks
- name: gcp-stemcell-version
  type: semver
  source:
    bucket: bosh-windows-stemcells
    key: versions/gcp-stemcell-version-edge
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
    initial_version: 1000.0.0
- name: gcp-stemcell-release-candidate
  type: s3
  source:
    bucket: bosh-windows-stemcells-release-candidates
    regexp: light-bosh-stemcell-(.*)-google-kvm-windows2012R2-go_agent.tgz
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: gcp-stemcell-final
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: light-bosh-stemcell-(.*)-google-kvm-windows2012R2-go_agent.tgz
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}

jobs:
- name: build-stemcells
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: bosh-agent
    - get: stemcell-builder
    - get: base-iso
    - get: windows-stemcell-dependencies
    - get: version
      resource: stemcells-major-version
      params:
        bump: major
  - put: stemcells-major-version
    params:
      file: version/number
  - aggregate:
    - put: vsphere-stemcell-version
      params:
        file: version/number
    - put: aws-stemcell-version
      params:
        file: version/number
    - put: gcp-stemcell-version
      params:
        file: version/number
  - task: collect-win2012r2-amis
    file: ci/tasks/collect-base-amis.yml
    output_mapping: { base-amis: win2012r2-amis }
    params:
      AWS_ACCESS_KEY_ID: {{BOSH_WINDOWS_AWS_READ_VPC_EC2_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: {{BOSH_WINDOWS_AWS_READ_VPC_EC2_SECRET_ACCESS_KEY}}
      BASE_AMI: windows2012R2
  - task: collect-win2012r2-gcp-image
    file: ci/tasks/get-base-gcp-image-id.yml
    output_mapping: { base-gcp-image: win2012r2-gcp-image }
    params:
      ACCOUNT_JSON: {{MUSTANG_GCP_STEMCELLS_ACCOUNT_JSON}}
      BASE_OS: windows2012R2
  - put: base-amis-win2012r2
    params:
      file: win2012r2-amis/base-amis-windows2012R2-*.json
  - put: base-gcp-image-win2012r2
    params:
      file: win2012r2-gcp-image/base-gcp-image-windows2012R2-*.json
- name: create-vsphere-stemcell
  serial: true
  serial_groups: [vsphere]
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere-windows]
    - get: bosh-agent
      tags: [vsphere-windows]
    - get: stemcell-builder
      tags: [vsphere-windows]
    - get: windows-stemcell-dependencies
      tags: [vsphere-windows]
    - get: version
      tags: [vsphere-windows]
      resource: vsphere-stemcell-version
      passed: [build-stemcells]
      trigger: true
    - get: vmx-version
      tags: [vsphere-windows]
      resource: updated-vmx-version
  - put: version
    resource: vsphere-stemcell-version
    params:
      pre: build
  - task: create-stemcell
    privileged: true
    file: stemcell-builder/tasks/create-vsphere-stemcell.yml
    tags: [vsphere-windows-worker]
    params:
      ADMINISTRATOR_PASSWORD: "Password123!"
      PRODUCT_KEY: {{PRODUCT_KEY}}
      ORGANIZATION: Pivotal
      OWNER: Pivotal
      AWS_ACCESS_KEY_ID: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
      AWS_REGION: us-east-1
- name: test-vsphere-stemcell
  serial: true
  serial_groups: [vsphere]
  plan:
  - aggregate:
    - get: ci
      passed: [create-vsphere-stemcell]
    - get: bosh-agent
      passed: [create-vsphere-stemcell]
    - get: bosh-windows-stemcell
      tags: [vsphere-windows]
      resource: vsphere-stemcell-pre-release-candidate
      trigger: true
    - get: stemcell-builder
      passed: [create-vsphere-stemcell]
    - get: version
      resource: vsphere-stemcell-version
      passed: [create-vsphere-stemcell]
  - task: test-stemcell
    tags: [vsphere-windows]
    file: stemcell-builder/src/github.com/cloudfoundry-incubator/bosh-windows-acceptance-tests/ci/task.yml
    attempts: 5
    params:
      AZ: default
      VM_TYPE: xlarge
      BOSH_CLIENT_SECRET: {{STONETALON_BOSH_CLIENT_SECRET}}
      BOSH_CLIENT: {{STONETALON_BOSH_CLIENT_ID}}
      DIRECTOR_UUID: {{STONETALON_DIRECTOR_UUID}}
      DIRECTOR_IP: {{STONETALON_BOSH_DIRECTOR_IP}}
      STEMCELL_NAME: bosh-vsphere-esxi-windows-2012R2-go_agent
      STEMCELL_PATH: bosh-windows-stemcell/bosh-stemcell-*-vsphere-esxi-windows2012R2-go_agent.tgz
      BOSH_CA_CERT: {{STONETALON_BOSH_TARGET_CERT}}
  - put: vsphere-stemcell-release-candidate
    params:
      file: bosh-windows-stemcell/bosh-stemcell-*-vsphere-esxi-windows2012R2-go_agent.tgz
- name: create-vsphere-add-updates
  serial: true
  serial_groups: [vsphere]
  plan:
  - aggregate:
    - get: ci
    - get: stemcell-builder
    - get: windows-stemcell-dependencies
    - get: vmx-version
      resource: updated-vmx-version
  - task: add-updates
    privileged: true
    file: stemcell-builder/tasks/create-vsphere-add-updates-stemcell.yml
    tags: [vsphere-windows-worker]
    params:
      ADMINISTRATOR_PASSWORD: "Password123!"
      AWS_ACCESS_KEY_ID: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
      AWS_REGION: us-east-1
  - put: updated-vmx-version
    params: {bump: major}
- name: create-aws-stemcell
  serial: true
  plan:
  - put: aws-lock
    params:
      acquire: true
  - do:
    - aggregate:
      - get: ci
      - get: stemcell-builder
        passed: [build-stemcells]
      - get: bosh-agent
        passed: [build-stemcells]
      - get: base-amis
        resource: base-amis-win2012r2
        passed: [build-stemcells]
      - get: version
        resource: aws-stemcell-version
        passed: [build-stemcells]
        trigger: true
      - get: windows-stemcell-dependencies
    - put: version
      resource: aws-stemcell-version
      params:
        pre: build
    - task: create-stemcell
      file: stemcell-builder/tasks/create-aws-stemcell.yml
      params:
        OS_VERSION: windows2012R2
        AWS_ACCESS_KEY: {{BOSH_WINDOWS_AWS_STEMCELLS_ACCESS_KEY_ID}}
        AWS_SECRET_KEY: {{BOSH_WINDOWS_AWS_STEMCELLS_SECRET_ACCESS_KEY}}
      ensure:
        task: delete-orphan-vms
        file: ci/tasks/delete-vms.yml
        params:
          AWS_ACCESS_KEY_ID: {{BOSH_WINDOWS_AWS_STEMCELLS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: {{BOSH_WINDOWS_AWS_STEMCELLS_SECRET_ACCESS_KEY}}
    - task: test-stemcell
      file: stemcell-builder/src/github.com/cloudfoundry-incubator/bosh-windows-acceptance-tests/ci/task.yml
      attempts: 5
      params:
        BOSH_CLIENT_SECRET: {{BOSH_CONCOURSE_BOSH_PASSWORD}}
        BOSH_CLIENT: {{BOSH_CONCOURSE_BOSH_USER}}
        DIRECTOR_IP: {{BOSH_CONCOURSE_DIRECTOR_IP}}
        DIRECTOR_UUID: 54af1a2c-c84e-4a95-a723-3771ec7da4d9
        STEMCELL_NAME: bosh-aws-xen-hvm-windows-stemcell-go_agent
        STEMCELL_PATH: bosh-windows-stemcell/light-bosh-stemcell-*-aws-xen-hvm-windows2012R2-go_agent.tgz
        BOSH_CA_CERT: {{BOSH_CONCOURSE_BOSH_TARGET_CERT}}
    - put: aws-stemcell-release-candidate
      params:
        file: bosh-windows-stemcell/light-bosh-stemcell-*-aws-xen-hvm-windows2012R2-go_agent.tgz
    - put: aws-stemcell-sha
      params:
        file: sha/light-bosh-stemcell-*-aws-xen-hvm-windows2012R2-go_agent.tgz.sha
    ensure:
      put: aws-lock
      params:
        release: aws-lock
- name: create-gcp-stemcell
  serial: true
  plan:
  - put: gcp-lock
    params:
      acquire: true
  - do:
    - aggregate:
      - get: ci
      - get: stemcell-builder
        passed: [build-stemcells]
      - get: bosh-agent
        passed: [build-stemcells]
      - get: base-gcp-image
        resource: base-gcp-image-win2012r2
        passed: [build-stemcells]
      - get: version
        resource: gcp-stemcell-version
        passed: [build-stemcells]
        trigger: true
      - get: windows-stemcell-dependencies
    - put: version
      resource: gcp-stemcell-version
      params:
        pre: build
    - task: create-stemcell
      file: stemcell-builder/tasks/create-gcp-stemcell.yml
      params:
        OS_VERSION: windows2012R2
        ACCOUNT_JSON: {{MUSTANG_GCP_STEMCELLS_ACCOUNT_JSON}}
    - task: test-stemcell
      file: stemcell-builder/src/github.com/cloudfoundry-incubator/bosh-windows-acceptance-tests/ci/task.yml
      params:
        IAAS: gcp
        ACCOUNT_JSON: {{OTTER_GCP_BOSH_ACCOUNT_JSON}}
        BOSH_CLIENT_SECRET: {{OTTER_BOSH_PASSWORD}}
        BOSH_CLIENT: {{OTTER_BOSH_USER}}
        DIRECTOR_IP: {{OTTER_DIRECTOR_IP}}
        DIRECTOR_UUID: {{OTTER_DIRECTOR_UUID}}
        STEMCELL_NAME: bosh-google-kvm-windows2012R2-go_agent
        STEMCELL_PATH: bosh-windows-stemcell/light-bosh-stemcell-*-google-kvm-windows2012R2-go_agent.tgz
        BOSH_CA_CERT: {{OTTER_BOSH_TARGET_CERT}}
    - put: gcp-stemcell-release-candidate
      params:
        file: bosh-windows-stemcell/light-bosh-stemcell-*-google-kvm-windows2012R2-go_agent.tgz
    ensure:
      put: gcp-lock
      params:
        release: gcp-lock
- name: promote-stemcells
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: vsphere-stemcell-release-candidate
      tags: [vsphere-windows]
      passed: [test-vsphere-stemcell]
    - get: aws-stemcell-release-candidate
      passed: [create-aws-stemcell]
    - get: aws-stemcell-sha
      passed: [create-aws-stemcell]
    - get: gcp-stemcell-release-candidate
      passed: [create-gcp-stemcell]
    - get: bosh-agent
      passed: [create-gcp-stemcell,create-aws-stemcell,test-vsphere-stemcell]
    - get: stemcell-builder
      passed: [create-gcp-stemcell,create-aws-stemcell,test-vsphere-stemcell]
  - task: ensure-versions-match
    tags: [vsphere-windows]
    file: ci/tasks/ensure-versions-match.yml
  - aggregate:
    - task: set-stemcell-version
      tags: [vsphere-windows]
      input_mapping: { bosh-windows-stemcell: vsphere-stemcell-release-candidate }
      output_mapping: { final-stemcell: vsphere-stemcell-final }
      file: ci/tasks/set-stemcell-version.yml
    - task: set-stemcell-version
      tags: [vsphere-windows]
      input_mapping: { bosh-windows-stemcell: aws-stemcell-release-candidate }
      output_mapping: { final-stemcell: aws-stemcell-final }
      file: ci/tasks/set-stemcell-version.yml
    - task: set-stemcell-version
      tags: [vsphere-windows]
      input_mapping: { bosh-windows-stemcell: gcp-stemcell-release-candidate }
      output_mapping: { final-stemcell: gcp-stemcell-final }
      file: ci/tasks/set-stemcell-version.yml
  - task: create-major-stemcell
    tags: [vsphere-windows]
    file: ci/tasks/create-major-stemcell.yml
    input_mapping: { final-stemcell: aws-stemcell-final }
  - put: major-stemcell
    tags: [vsphere-windows]
    params:
      file: stemcell-info/stemcell-*.json
  - put: vsphere-stemcell-final
    tags: [vsphere-windows]
    params:
      file: vsphere-stemcell-final/bosh-stemcell-*-vsphere-esxi-windows2012R2-go_agent.tgz
  - put: aws-stemcell-final
    tags: [vsphere-windows]
    params:
      file: aws-stemcell-final/light-bosh-stemcell-*-aws-xen-hvm-windows2012R2-go_agent.tgz
  - task: post-boshio-aws-stemcell-sha
    tags: [vsphere-windows]
    file: ci/tasks/post-boshio-stemcell-sha.yml
    input_mapping: { sha: aws-stemcell-sha }
    params:
      BOSHIO_TOKEN: {{BOSHIO_TOKEN}}
  - put: gcp-stemcell-final
    tags: [vsphere-windows]
    params:
      file: gcp-stemcell-final/light-bosh-stemcell-*-google-kvm-windows2012R2-go_agent.tgz
