resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: bosh-windows-stemcells-major-version
  type: semver
  source:
    bucket: bosh-windows-stemcells
    key: versions/stemcells-major-version
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
    initial_version: 1007.0.0
- name: bosh-agent
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-agent.git
- name: stemcell-builder
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-builder.git
- name: windows-stemcell-dependencies
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-cf/windows-stemcell-dependencies.git
    private_key: {{PIVOTAL-CF_WINDOWS-STEMCELL-DEPENDENCIES_PRIVATE_KEY}}
- name: base-iso
  type: s3
  source:
    bucket: windows-bosh-private
    regexp: en_windows_server_2012_r2_x64_dvd_(.*).iso
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: bosh-vsphere-stemcell-version
  type: semver
  source:
    bucket: bosh-windows-stemcells
    key: versions/vsphere-stemcell-version
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
    initial_version: 1000.0.0
- name: bosh-vsphere-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: bosh-stemcell-(.*)-vsphere-esxi-windows2012R2-go_agent.tgz
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: bosh-aws-stemcell-version
  type: semver
  source:
    bucket: bosh-windows-stemcells
    key: versions/aws-stemcell-version
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
    initial_version: 1000.0.0
- name: bosh-aws-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: light-bosh-stemcell-(.*)-aws-xen-hvm-windows2012R2-go_agent.tgz
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: base-amis-version
  type: semver
  source:
    bucket: bosh-windows-stemcells
    key: versions/base-amis-version
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
    initial_version: 1.0.0
- name: base-amis
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: base-amis-(.*).json
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: bosh-gcp-stemcell-version
  type: semver
  source:
    bucket: bosh-windows-stemcells
    key: versions/gcp-stemcell-version
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
    initial_version: 1000.0.0
- name: bosh-gcp-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: light-bosh-stemcell-(.*)-google-kvm-windows2012R2-go_agent.tgz
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: bwats
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/bosh-windows-acceptance-tests.git

jobs:
- name: bump-base-amis
  serial: true
  plan:
  - get: version
    resource: base-amis-version
  - 
- name: build-stemcells
  serial: true
  plan:
  - aggregate:
    - get: bosh-agent
    - get: stemcell-builder
    - get: bwats
    - get: version
      resource: bosh-windows-stemcells-major-version
      params:
        bump: major
    - get: 
  - put: bosh-windows-stemcells-major-version
    params:
      file: version/number
  - put: bosh-vsphere-stemcell-version
    params:
      file: version/number
  - put: bosh-aws-stemcell-version
    params:
      file: version/number
  - put: bosh-gcp-stemcell-version
    params:
      file: version/number
  - task: collect-amis
    file: ci/tasks/collect-stemcell-region-amis.yml
    params:
      AWS_ACCESS_KEY_ID: {{BOSH_WINDOWS_AWS_READ_VPC_EC2_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: {{BOSH_WINDOWS_AWS_READ_VPC_EC2_SECRET_ACCESS_KEY}}
  - put: base-amis
- name: create-vsphere-stemcell
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: bosh-agent
      passed: [build-stemcells]
      trigger: true
    - get: stemcell-builder
      passed: [build-stemcells]
      trigger: true
    - get: windows-stemcell-dependencies
      tags: [vsphere-windows]
    - get: base-iso
      tags: [vsphere-windows]
    - put: version
      resource: bosh-vsphere-stemcell-version
      params:
        pre: build
    - get: bwats
      passed: [build-stemcells]
      trigger: true
  - task: compile-bosh-agent
    file: ci/tasks/compile-bosh-agent.yml
    tags: [vsphere-windows]
  - task: create-vsphere-stemcell
    privileged: true
    file: stemcell-builder/tasks/create-vsphere-stemcell.yml
    tags: [vsphere-windows]
    params:
      OUTPUT_DIR: bosh-windows-stemcell
      ISO_CHECKSUM_TYPE: "md5"
      ISO_CHECKSUM: "0e7c09aab20dec3cd7eab236dab90e78"
      MEMSIZE: "8192"
      NUMVCPUS: "6"
      REMOTE_HOST: {{ESXI_REMOTE_ADDRESS}}
      REMOTE_PORT: "22"
      REMOTE_DATASTORE: "578921d3-1b48ca03-9708-02505600004b"
      REMOTE_CACHE_DATASTORE: "578921d3-1b48ca03-9708-02505600004b"
      REMOTE_CACHE_DIRECTORY: "packer-cache"
      REMOTE_USERNAME: {{ESXI_REMOTE_USER}}
      REMOTE_PASSWORD: {{ESXI_REMOTE_PASSWORD}}
      ADMINISTRATOR_PASSWORD: {{WINDOWS_PASSWORD}}
      GUEST_NETWORK_ADDRESS: "10.85.58.10"
      GUEST_NETWORK_MASK: "255.255.255.0"
      GUEST_NETWORK_GATEWAY: "10.85.58.1"
    ensure:
      task: cleanup-vsphere
      file: ci/tasks/cleanup-vsphere.yml
      tags: [vsphere-windows]
      params:
        REMOTE_HOST: {{ESXI_REMOTE_ADDRESS}}
        REMOTE_USERNAME: {{ESXI_REMOTE_USER}}
        REMOTE_PASSWORD: {{ESXI_REMOTE_PASSWORD}}
        REMOTE_DATASTORE: "578921d3-1b48ca03-9708-02505600004b"
  - task: test-stemcell
    file: bwats/ci/task.yml
    attempts: 5
    tags: [vsphere-windows]
    params:
      AZ: default
      VM_TYPE: xlarge
      BOSH_CLIENT_SECRET: {{STONETALON_BOSH_CLIENT_SECRET}}
      BOSH_CLIENT: {{STONETALON_BOSH_CLIENT_ID}}
      DIRECTOR_UUID: {{STONETALON_DIRECTOR_UUID}}
      DIRECTOR_IP: {{STONETALON_BOSH_DIRECTOR_IP}}
      STEMCELL_NAME: bosh-vsphere-esxi-windows-2012R2-go_agent
      STEMCELL_PATH: bosh-windows-stemcell/bosh-stemcell-*-vsphere-esxi-windows2012R2-go_agent.tgz
      BOSH_CA_CERT: {{STONETALON_BOSH_TARGET_CERT}}
  - put: version
    resource: bosh-vsphere-stemcell-version
    params:
      bump: final
  - task: set-stemcell-version
    tags: [vsphere-windows]
    file: ci/tasks/set-stemcell-version.yml
  - put: bosh-vsphere-stemcell
    tags: [vsphere-windows]
    params:
      file: final-stemcell/bosh-stemcell-*-vsphere-esxi-windows2012R2-go_agent.tgz
- name: create-aws-stemcell
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: stemcell-builder
      passed: [build-stemcells]
      trigger: true
    - get: bosh-agent
      passed: [build-stemcells]
      trigger: true
    - get: base-amis
      passed: [build-stemcells]
    - put: version
      resource: bosh-aws-stemcell-version
      params:
        pre: build
    - get: bwats
      passed: [build-stemcells]
      trigger: true
  - task: compile-bosh-agent
    file: ci/tasks/compile-bosh-agent.yml
  - task: create-stemcell
    file: stemcell-builder/tasks/create-aws-stemcell.yml
    params:
      OUTPUT_DIR: bosh-windows-stemcell
      OS_VERSION: windows2012R2
      AWS_ACCESS_KEY: {{BOSH_WINDOWS_AWS_STEMCELLS_ACCESS_KEY_ID}}
      AWS_SECRET_KEY: {{BOSH_WINDOWS_AWS_STEMCELLS_SECRET_ACCESS_KEY}}
    ensure:
      task: delete-orphan-vms
      file: ci/tasks/delete-vms.yml
      params:
        AWS_ACCESS_KEY_ID: {{BOSH_WINDOWS_AWS_STEMCELLS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: {{BOSH_WINDOWS_AWS_STEMCELLS_SECRET_ACCESS_KEY}}
  - task: test-stemcell
    file: bwats/ci/task.yml
    attempts: 5
    params:
      BOSH_CLIENT_SECRET: {{BOSH_CONCOURSE_BOSH_PASSWORD}}
      BOSH_CLIENT: {{BOSH_CONCOURSE_BOSH_USER}}
      DIRECTOR_IP: {{BOSH_CONCOURSE_DIRECTOR_IP}}
      DIRECTOR_UUID: 54af1a2c-c84e-4a95-a723-3771ec7da4d9
      STEMCELL_NAME: bosh-aws-xen-hvm-windows-stemcell-go_agent
      STEMCELL_PATH: bosh-windows-stemcell/light-bosh-stemcell-*-aws-xen-hvm-windows2012R2-go_agent.tgz
      BOSH_CA_CERT: {{BOSH_CONCOURSE_BOSH_TARGET_CERT}}
  - put: version
    resource: bosh-aws-stemcell-version
    params:
      bump: final
  - task: set-stemcell-version
    file: ci/tasks/set-stemcell-version.yml
  - put: bosh-aws-stemcell
    params:
      file: final-stemcell/light-bosh-stemcell-*-aws-xen-hvm-windows2012R2-go_agent.tgz
- name: create-gcp-stemcell
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: stemcell-builder
      passed: [build-stemcells]
      trigger: true
    - get: bosh-agent
      passed: [build-stemcells]
      trigger: true
    - put: version
      resource: bosh-gcp-stemcell-version
      params:
        pre: build
    - get: bwats
      passed: [build-stemcells]
      trigger: true
  - task: compile-bosh-agent
    file: ci/tasks/compile-bosh-agent.yml
  - task: create-stemcell
    attempts: 10
    file: stemcell-builder/tasks/create-gcp-stemcell.yml
    params:
      OUTPUT_DIR: bosh-windows-stemcell
      OS_VERSION: windows2012R2
      ACCOUNT_JSON: {{MUSTANG_GCP_STEMCELLS_ACCOUNT_JSON}}
  - task: test-stemcell
    file: bwats/ci/task.yml
    attempts: 5
    params:
      IAAS: gcp
      ACCOUNT_JSON: {{OTTER_GCP_BOSH_ACCOUNT_JSON}}
      BOSH_CLIENT_SECRET: {{OTTER_BOSH_PASSWORD}}
      BOSH_CLIENT: {{OTTER_BOSH_USER}}
      DIRECTOR_IP: {{OTTER_DIRECTOR_IP}}
      DIRECTOR_UUID: {{OTTER_DIRECTOR_UUID}}
      STEMCELL_NAME: bosh-google-kvm-windows2012R2-go_agent
      STEMCELL_PATH: bosh-windows-stemcell/light-bosh-stemcell-*-google-kvm-windows2012R2-go_agent.tgz
      BOSH_CA_CERT: {{OTTER_BOSH_TARGET_CERT}}
  - put: version
    resource: bosh-gcp-stemcell-version
    params:
      bump: final
  - task: set-stemcell-version
    file: ci/tasks/set-stemcell-version.yml
  - put: bosh-gcp-stemcell
    params:
      file: final-stemcell/light-bosh-stemcell-*-google-kvm-windows2012R2-go_agent.tgz
