groups:
- name: all
  jobs:
  - dolphin-deploy-cf
  - dolphin-destroy-cf
  - baboon-deploy-cf
  - baboon-destroy-cf
  - ferret-deploy-cf
  - ferret-destroy-cf
  - mulgore-deploy-cf
  - mulgore-destroy-cf
- name: dolphin
  jobs:
  - dolphin-deploy-cf
  - dolphin-destroy-cf
- name: baboon
  jobs:
  - baboon-deploy-cf
  - baboon-destroy-cf
- name: ferret
  jobs:
  - ferret-deploy-cf
  - ferret-destroy-cf
- name: mulgore
  jobs:
  - mulgore-deploy-cf
  - mulgore-destroy-cf

resources:
- name: cf-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment.git
- name: greenhouse-private
  type: git
  source:
    branch: master
    private_key: {{GREENHOUSE_CI_GITHUB_PRIVATE_KEY}}
    uri: git@github.com:pivotal-cf/greenhouse-private
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: aws-windows-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells-release-candidates
    regexp: light-bosh-stemcell-(.*)-aws-xen-hvm-windows2012R2-go_agent.tgz
- name: gcp-windows-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells-release-candidates
    regexp: light-bosh-stemcell-(.*)-google-kvm-windows2012R2-go_agent.tgz
- name: vsphere-windows-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells-private-release-candidates
    regexp: bosh-stemcell-(.*)-vsphere-esxi-windows2012R2-go_agent.tgz
- name: aws-linux-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
- name: gcp-linux-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent
- name: vsphere-linux-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
- name: wats
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/wats.git
- name: weekly-trigger
  type: time
  source:
    days: [Saturday]
    location: US/Eastern
    start: 12:00 AM
    stop: 1:00 AM
- name: dolphin-lock-pool
  type: pool
  source:
    branch: master
    pool: dolphin
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks
- name: baboon-lock-pool
  type: pool
  source:
    branch: master
    pool: baboon
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks
- name: ferret-lock-pool
  type: pool
  source:
    branch: master
    pool: ferret
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks
- name: mulgore-lock-pool
  type: pool
  source:
    branch: master
    pool: mulgore
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks

jobs:
- name: dolphin-deploy-cf
  serial: true
  plan:
  - put: dolphin-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: cf-deployment
      - get: greenhouse-private
      - get: ci
      - get: windows-stemcell
        resource: gcp-windows-stemcell
      - get: linux-stemcell
        resource: gcp-linux-stemcell
      - get: wats
      - get: weekly-trigger
        trigger: true
    - task: upload-linux-stemcell
      file: ci/tasks/upload-stemcell.yml
      params:
        BOSH_CLIENT: {{DOLPHIN_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{DOLPHIN_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{DOLPHIN_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{DOLPHIN_BOSH_CA_CERT}}
    - task: deploy-cf
      file: ci/tasks/cf-deployment-with-windows.yml
      params:
        ENVIRONMENT: dolphin
        BOSH_CLIENT: {{DOLPHIN_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{DOLPHIN_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{DOLPHIN_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{DOLPHIN_BOSH_CA_CERT}}
        CF_DOMAIN: dolphin.cf-app.com
    - put: greenhouse-private
      params:
        repository: output/greenhouse-private
        rebase: true
    - task: clean-up
      file: ci/tasks/clean-up.yml
      params:
        BOSH_CLIENT: {{DOLPHIN_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{DOLPHIN_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{DOLPHIN_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{DOLPHIN_BOSH_CA_CERT}}
    - task: wats
      file: ci/tasks/run-wats.yml
      params:
        ADMIN_PASSWORD: {{DOLPHIN_ADMIN_PASSWORD}}
        ADMIN_USER: admin
        API: api.dolphin.cf-app.com
        APPS_DOMAIN: dolphin.cf-app.com
        NUM_WIN_CELLS: 1
        SOCKET_ADDRESS_FOR_SECURITY_GROUP_TEST: 10.0.0.6:25555
    ensure:
      put: dolphin-lock-pool
      params:
        release: dolphin-lock-pool

- name: dolphin-destroy-cf
  serial: true
  plan:
  - put: dolphin-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: ci
    - task: destroy-cf
      file: ci/tasks/delete-deployment.yml
      params:
        BOSH_CLIENT: {{DOLPHIN_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{DOLPHIN_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{DOLPHIN_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{DOLPHIN_BOSH_CA_CERT}}
    ensure:
      put: dolphin-lock-pool
      params:
        release: dolphin-lock-pool

- name: baboon-deploy-cf
  serial: true
  plan:
  - put: baboon-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: cf-deployment
      - get: greenhouse-private
      - get: ci
      - get: windows-stemcell
        resource: gcp-windows-stemcell
      - get: linux-stemcell
        resource: gcp-linux-stemcell
      - get: wats
      - get: weekly-trigger
        trigger: true
    - task: upload-linux-stemcell
      file: ci/tasks/upload-stemcell.yml
      params:
        BOSH_CLIENT: {{BABOON_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{BABOON_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{BABOON_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{BABOON_BOSH_CA_CERT}}
    - task: deploy-cf
      file: ci/tasks/cf-deployment-with-windows.yml
      params:
        ENVIRONMENT: baboon
        BOSH_CLIENT: {{BABOON_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{BABOON_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{BABOON_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{BABOON_BOSH_CA_CERT}}
        CF_DOMAIN: baboon.cf-app.com
    - put: greenhouse-private
      params:
        repository: output/greenhouse-private
        rebase: true
    - task: clean-up
      file: ci/tasks/clean-up.yml
      params:
        BOSH_CLIENT: {{BABOON_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{BABOON_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{BABOON_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{BABOON_BOSH_CA_CERT}}
    - task: wats
      file: ci/tasks/run-wats.yml
      params:
        ADMIN_PASSWORD: {{BABOON_ADMIN_PASSWORD}}
        ADMIN_USER: admin
        API: api.baboon.cf-app.com
        APPS_DOMAIN: baboon.cf-app.com
        NUM_WIN_CELLS: 1
        SOCKET_ADDRESS_FOR_SECURITY_GROUP_TEST: 10.0.0.6:25555
    ensure:
      put: baboon-lock-pool
      params:
        release: baboon-lock-pool

- name: baboon-destroy-cf
  serial: true
  plan:
  - put: baboon-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: ci
    - task: destroy-cf
      file: ci/tasks/delete-deployment.yml
      params:
        BOSH_CLIENT: {{BABOON_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{BABOON_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{BABOON_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{BABOON_BOSH_CA_CERT}}
    ensure:
      put: baboon-lock-pool
      params:
        release: baboon-lock-pool

- name: ferret-deploy-cf
  serial: true
  plan:
  - put: ferret-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: cf-deployment
      - get: greenhouse-private
      - get: ci
      - get: windows-stemcell
        resource: aws-windows-stemcell
      - get: linux-stemcell
        resource: aws-linux-stemcell
      - get: wats
      - get: weekly-trigger
        trigger: true
    - task: upload-linux-stemcell
      file: ci/tasks/upload-stemcell.yml
      params:
        BOSH_CLIENT: {{FERRET_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{FERRET_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{FERRET_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{FERRET_BOSH_CA_CERT}}
    - task: deploy-cf
      file: ci/tasks/cf-deployment-with-windows.yml
      params:
        ENVIRONMENT: ferret
        BOSH_CLIENT: {{FERRET_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{FERRET_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{FERRET_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{FERRET_BOSH_CA_CERT}}
        CF_DOMAIN: greenhouse-ferret.cf-app.com
    - put: greenhouse-private
      params:
        repository: output/greenhouse-private
        rebase: true
    - task: clean-up
      file: ci/tasks/clean-up.yml
      params:
        BOSH_CLIENT: {{FERRET_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{FERRET_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{FERRET_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{FERRET_BOSH_CA_CERT}}
    - task: wats
      file: ci/tasks/run-wats.yml
      params:
        ADMIN_PASSWORD: {{FERRET_ADMIN_PASSWORD}}
        ADMIN_USER: admin
        API: api.greenhouse-ferret.cf-app.com
        APPS_DOMAIN: greenhouse-ferret.cf-app.com
        NUM_WIN_CELLS: 1
        SOCKET_ADDRESS_FOR_SECURITY_GROUP_TEST: 10.0.0.6:25555
    ensure:
      put: ferret-lock-pool
      params:
        release: ferret-lock-pool

- name: ferret-destroy-cf
  serial: true
  plan:
  - put: ferret-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: ci
    - task: destroy-cf
      file: ci/tasks/delete-deployment.yml
      params:
        BOSH_CLIENT: {{FERRET_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{FERRET_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{FERRET_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{FERRET_BOSH_CA_CERT}}
    ensure:
      put: ferret-lock-pool
      params:
        release: ferret-lock-pool

- name: mulgore-deploy-cf
  serial: true
  plan:
  - put: mulgore-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: cf-deployment
      - get: greenhouse-private
      - get: ci
      - get: windows-stemcell
        resource: vsphere-windows-stemcell
        tags: [vsphere]
        trigger: true
        tags: [vsphere]
      - get: linux-stemcell
        resource: vsphere-linux-stemcell
        tags: [vsphere]
      - get: wats
        trigger: true
    - task: upload-linux-stemcell
      file: ci/tasks/upload-stemcell.yml
      tags: [vsphere]
      params:
        BOSH_CLIENT: admin
        BOSH_CLIENT_SECRET: {{mulgore_client_secret}}
        BOSH_ENVIRONMENT: {{mulgore_environment}}
        BOSH_CA_CERT: {{mulgore_ca_cert}}
    - task: deploy-cf
      tags: [vsphere]
      file: ci/tasks/cf-deployment-with-windows.yml
      params:
        ENVIRONMENT: mulgore
        BOSH_CLIENT: admin
        BOSH_CLIENT_SECRET: {{mulgore_client_secret}}
        BOSH_ENVIRONMENT: {{mulgore_environment}}
        BOSH_CA_CERT: {{mulgore_ca_cert}}
        CF_DOMAIN: mulgore.cf-app.com
    - put: greenhouse-private
      params:
        repository: output/greenhouse-private
        rebase: true
    - task: clean-up
      file: ci/tasks/clean-up.yml
      tags: [vsphere]
      params:
        BOSH_CLIENT: admin
        BOSH_CLIENT_SECRET: {{mulgore_client_secret}}
        BOSH_ENVIRONMENT: {{mulgore_environment}}
        BOSH_CA_CERT: {{mulgore_ca_cert}}
    - task: wats
      tags: [vsphere]
      file: ci/tasks/run-wats.yml
      params:
        ADMIN_PASSWORD: {{mulgore_cf_admin_password}}
        ADMIN_USER: admin
        API: api.mulgore.cf-app.com
        APPS_DOMAIN: mulgore.cf-app.com
        NUM_WIN_CELLS: 1
        SOCKET_ADDRESS_FOR_SECURITY_GROUP_TEST: 10.85.51.16:25555
    ensure:
      put: mulgore-lock-pool
      params:
        release: mulgore-lock-pool

- name: mulgore-destroy-cf
  serial: true
  plan:
  - put: mulgore-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: ci
    - task: destroy-cf
      file: ci/tasks/delete-deployment.yml
      tags: [vsphere]
      params:
        BOSH_CLIENT: admin
        BOSH_CLIENT_SECRET: {{mulgore_client_secret}}
        BOSH_ENVIRONMENT: {{mulgore_environment}}
        BOSH_CA_CERT: {{mulgore_ca_cert}}
    ensure:
      put: mulgore-lock-pool
      params:
        release: mulgore-lock-pool
