resources:
- name: cf-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment.git
- name: greenhouse-private
  type: git
  source:
    branch: master
    private_key: {{GREENHOUSE_CI_GITHUB_PRIVATE_KEY}}
    uri: git@github.com:pivotal-cf/greenhouse-private
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: windows-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: light-bosh-stemcell-(.*)-aws-xen-hvm-windows2012R2-go_agent.tgz
- name: linux-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
- name: weekly-trigger
  type: time
  source:
    days: [Saturday]
    location: US/Eastern
    start: 12:00 AM
    stop: 1:00 AM

jobs:
- name: upload-stemcell
  serial: true
  plan:
  - aggregate:
    - get: linux-stemcell
      trigger: true
  - task: upload-stemcell
    params:
      BOSH_CLIENT: {{FERRET_BOSH_CLIENT}}
      BOSH_CLIENT_SECRET: {{FERRET_BOSH_CLIENT_SECRET}}
      BOSH_ENVIRONMENT: {{FERRET_BOSH_ENVIRONMENT}}
      BOSH_CA_CERT: {{FERRET_BOSH_CA_CERT}}
    config:
      platform: linux
      image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/bosh-cli}}
      inputs:
      - name: linux-stemcell
      run:
        path: bosh
        args:
          - -n
          - upload-stemcell
          - linux-stemcell/stemcell.tgz
- name: deploy-cf
  serial: true
  plan:
  - aggregate:
    - get: cf-deployment
      trigger: true
    - get: greenhouse-private
    - get: ci
    - get: windows-stemcell
    - get: weekly-trigger
      trigger: true
  - task: deploy-cf
    file: ci/tasks/cf-deployment-with-windows.yml
    params:
      ENVIRONMENT: ferret
      BOSH_CLIENT: {{FERRET_BOSH_CLIENT}}
      BOSH_CLIENT_SECRET: {{FERRET_BOSH_CLIENT_SECRET}}
      BOSH_ENVIRONMENT: {{FERRET_BOSH_ENVIRONMENT}}
      BOSH_CA_CERT: {{FERRET_BOSH_CA_CERT}}
      CF_DOMAIN: greenhouse-ferret.cf-app.com
  - task: save-cf-vars
    file: ci/tasks/save-cf-vars.yml
    params:
      ENVIRONMENT: ferret
      GITHUB_SSH_KEY: {{GREENHOUSE_CI_GITHUB_PRIVATE_KEY}}
  - task: clean-up
    params:
      BOSH_CLIENT: {{FERRET_BOSH_CLIENT}}
      BOSH_CLIENT_SECRET: {{FERRET_BOSH_CLIENT_SECRET}}
      BOSH_ENVIRONMENT: {{FERRET_BOSH_ENVIRONMENT}}
      BOSH_CA_CERT: {{FERRET_BOSH_CA_CERT}}
    config:
      platform: linux
      image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/bosh-cli}}
      run:
        path: bosh
        args:
          - -n
          - clean-up
          - --all
