resources:
- name: cf-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment.git
- name: greenhouse-private
  type: git
  source:
    branch: mulgore
    private_key: {{GREENHOUSE_CI_GITHUB_PRIVATE_KEY}}
    uri: git@github.com:pivotal-cf/greenhouse-private
- name: ci
  type: git
  source:
    branch: greenhouse-pipeline
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: vsphere-windows-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: bosh-stemcell-(.*)-vsphere-esxi-windows2012R2-go_agent.tgz

jobs:
- name: mulgore-deploy-cf
  serial: true
  plan:
  - aggregate:
    - get: cf-deployment
      trigger: true
    - get: greenhouse-private
    - get: ci
    - get: vsphere-windows-stemcell
      trigger: true
      tags: [vsphere]
  - task: deploy-cf
    tags: [vsphere]
    file: ci/tasks/cf-deployment-with-windows.yml
    params:
      ENVIRONMENT: mulgore
      BOSH_CLIENT: {{MULGORE_BOSH_CLIENT}}
      BOSH_CLIENT_SECRET: {{MULGORE_BOSH_CLIENT_SECRET}}
      BOSH_ENVIRONMENT: {{MULGORE_BOSH_ENVIRONMENT}}
      BOSH_CA_CERT: {{MULGORE_BOSH_CA_CERT}}
    on_failure:
      task: cleanup-deployment
      tags: [vsphere]
      file: ci/tasks/cleanup-cf-deployment.yml
      params:
        ENVIRONMENT: mulgore
        BOSH_CLIENT: {{MULGORE_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{MULGORE_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{MULGORE_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{MULGORE_BOSH_CA_CERT}}
  - task: save-cf-vars
    file: ci/tasks/save-cf-vars.yml
    params:
      ENVIRONMENT: mulgore
      GITHUB_SSH_KEY: {{GREENHOUSE_CI_GITHUB_PRIVATE_KEY}}
