resources:
- name: greenhouse-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: hwc-buildpack
  type: git
  source:
    branch: master
    uri: https://github.com/greenhouse-org/hwc-buildpack.git
- name: mulgore-lock-pool
  type: pool
  source:
    branch: master
    pool: mulgore
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks

resource_types: []

jobs:
- name: specs-hwc-buildpack
  serial: true
  plan:
  - put: mulgore-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: buildpack
        resource: hwc-buildpack
      - get: greenhouse-ci
    - task: run-machete-specs
      tags: [vsphere]
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: { repository: cfbuildpacks/ci }
        inputs:
        - name: buildpack
        - name: greenhouse-ci
        run: { path: greenhouse-ci/scripts/run-buildpack-specs.sh }
        params:
          STACK: windows2012R2
          CF_PASSWORD: {{MULGORE_CF_PASSWORD}}
          HOST: mulgore.cf-app.com
    ensure:
      put: mulgore-lock-pool
      params:
        release: mulgore-lock-pool
