resources:
- name: cf-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment.git
- name: greenhouse-private
  type: git
  source:
    branch: master
    private_key: {{GREENHOUSE_CI_GITHUB_PRIVATE_KEY}}
    uri: git@github.com:pivotal-cf/greenhouse-private
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: windows-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: bosh-stemcell-(.*)-vsphere-esxi-windows2012R2-go_agent.tgz
- name: linux-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
- name: wats
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/wats.git

jobs:
- name: upload-stemcell
  serial: true
  plan:
  - aggregate:
    - get: linux-stemcell
      trigger: true
  - task: upload-stemcell
    tags: [vsphere]
    params:
      BOSH_CLIENT: {{MULGORE_BOSH_CLIENT}}
      BOSH_CLIENT_SECRET: {{MULGORE_BOSH_CLIENT_SECRET}}
      BOSH_ENVIRONMENT: {{MULGORE_BOSH_ENVIRONMENT}}
      BOSH_CA_CERT: {{MULGORE_BOSH_CA_CERT}}
    config:
      platform: linux
      image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/bosh-cli}}
      inputs:
      - name: linux-stemcell
      run:
        path: bosh
        args:
          - -n
          - upload-stemcell
          - linux-stemcell/stemcell.tgz
- name: mulgore-deploy-cf
  serial: true
  plan:
  - aggregate:
    - get: cf-deployment
      trigger: true
    - get: greenhouse-private
    - get: ci
    - get: windows-stemcell
      trigger: true
      tags: [vsphere]
    - get: wats
      trigger: true
  - task: deploy-cf
    tags: [vsphere]
    file: ci/tasks/cf-deployment-with-windows.yml
    params:
      ENVIRONMENT: mulgore
      BOSH_CLIENT: {{MULGORE_BOSH_CLIENT}}
      BOSH_CLIENT_SECRET: {{MULGORE_BOSH_CLIENT_SECRET}}
      BOSH_ENVIRONMENT: {{MULGORE_BOSH_ENVIRONMENT}}
      BOSH_CA_CERT: {{MULGORE_BOSH_CA_CERT}}
      CF_DOMAIN: mulgore.cf-app.com
  - task: save-cf-vars
    file: ci/tasks/save-cf-vars.yml
    params:
      ENVIRONMENT: mulgore
      GITHUB_SSH_KEY: {{GREENHOUSE_CI_GITHUB_PRIVATE_KEY}}
  - task: wats
    tags: [vsphere]
    file: ci/tasks/run-wats.yml
    params:
      ADMIN_PASSWORD: {{ADMIN_PASSWORD}}
      ADMIN_USER: admin
      API: api.mulgore.cf-app.com
      APPS_DOMAIN: mulgore.cf-app.com
      NUM_WIN_CELLS: 1
      SOCKET_ADDRESS_FOR_SECURITY_GROUP_TEST: 10.85.51.16:25555
  - task: clean-up
    tags: [vsphere]
    params:
      BOSH_CLIENT: {{MULGORE_BOSH_CLIENT}}
      BOSH_CLIENT_SECRET: {{MULGORE_BOSH_CLIENT_SECRET}}
      BOSH_ENVIRONMENT: {{MULGORE_BOSH_ENVIRONMENT}}
      BOSH_CA_CERT: {{MULGORE_BOSH_CA_CERT}}
    config:
      platform: linux
      image_resource: {type: docker-image, source: {repository: pivotalgreenhouse/bosh-cli}}
      run:
        path: bosh
        args:
          - -n
          - clean-up
          - --all
