resources:
- name: greenhouse-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: releng-service-account-add
  type: s3
  source:
    bucket: service-account-for-windows
    access_key_id: {{AWS_ACCESS_KEY_ID}}
    secret_access_key: {{AWS_SECRET_ACCESS_KEY}}
    versioned_file: add
    region_name: us-west-1
- name: releng-service-account-remove
  type: s3
  source:
    bucket: service-account-for-windows
    access_key_id: {{AWS_ACCESS_KEY_ID}}
    secret_access_key: {{AWS_SECRET_ACCESS_KEY}}
    versioned_file: remove
    region_name: us-west-1

jobs:
- name: add-gcp-service-account
  serial: true
  plan:
  - aggregate:
    - get: greenhouse-ci
    - get: releng-service-account-add
      trigger: true
  - task: add-service-account
    input_mapping:
      service-account: releng-service-account-add
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pivotalgreenhouse/bosh-cli
      inputs:
      - name: greenhouse-ci
      - name: service-account
      run:
        path: greenhouse-ci/scripts/add-gcp-service-account.sh
      params:
        ROLE: compute.imageUser
        ACCOUNT_JSON: {{MUSTANG_GCP_STEMCELLS_ACCOUNT_JSON}}
- name: remove-gcp-service-account
  serial: true
  plan:
  - aggregate:
    - get: greenhouse-ci
    - get: releng-service-account-remove
      trigger: true
  - task: remove-service-account
    input_mapping:
      service-account: releng-service-account-remove
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pivotalgreenhouse/bosh-cli
      inputs:
      - name: greenhouse-ci
      - name: service-account
      run:
        path: greenhouse-ci/scripts/remove-gcp-service-account.sh
      params:
        ROLE: compute.imageUser
        ACCOUNT_JSON: {{MUSTANG_GCP_STEMCELLS_ACCOUNT_JSON}}

