resources:
- name: s3-bucket
  type: s3
  source:
    bucket: bosh-windows-dependencies
    regexp: tar-(.*).exe
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: bsdtar
  type: git
  source:
    branch: master
    uri: https://github.com/greenhouse-org/bsdtar.git

resource_types: []

jobs:
- name: build-tar
  serial: true
  plan:
  - aggregate:
    - get: bsdtar
      # trigger: true
    - get: s3-bucket
  - task: build-tar
    config:
      platform: windows
      inputs:
      - name: bsdtar
      outputs:
      - name: tar-output
      run:
        path: powershell
        args:
        - bsdtar/install.ps1
  - put: s3-bucket
    params:
      file: tar-output/tar-*.exe
