resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: winc-develop
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry-incubator/winc.git
- name: winc-master
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry-incubator/winc.git
    private_key: {{CLOUDFOUNDRYINCUBATOR_WINC_DEPLOY_KEY}}
- name: winc-release
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry-incubator/winc-release.git
    private_key: {{CLOUDFOUNDRYINCUBATOR_WINC-RELEASE_DEPLOY_KEY}}
- name: garden-runc-release
  type: git
  source:
    branch: gats
    uri: https://github.com/greenhouse-org/garden-runc-release.git
- name: pesto-winc-smoke-test-deployment
  type: bosh-deployment
  source:
    deployment: winc-smoke-test
    target: {{PESTO_BOSH_ENVIRONMENT}}
    client: {{PESTO_BOSH_CLIENT}}
    client_secret: {{PESTO_BOSH_CLIENT_SECRET}}
    ca_cert: {{PESTO_BOSH_CA_CERT}}
- name: stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells-release-candidates
    regexp: light-bosh-stemcell-(.*)-google-kvm-windows2016-go_agent.tgz
- name: pesto-lock-pool
  type: pool
  source:
    branch: master
    pool: pesto
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks

jobs:
- name: test
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: winc-develop
      trigger: true
    - get: winc-master
  - task: test-winc
    tags: [windows2016]
    input_mapping: { winc: winc-develop }
    file: ci/test-winc/task.yml
  - task: merge-develop-to-master
    input_mapping: { from-repo: winc-develop, to-repo: winc-master }
    file: ci/merge-repo/task.yml
    params: { FROM_BRANCH: develop }
  - put: winc-master
    params: { repository: merged-repo/to-repo }
- name: smoke-test
  serial: true
  plan:
  - put: pesto-lock-pool
    params:
      acquire: true
  - do:
    - aggregate:
      - get: ci
      - get: winc-release
      - get: stemcell
      - get: winc-master
        passed: [test]
        trigger: true
    - task: bump-submodule
      file: ci/bump-submodule/task.yml
      params:
        SUBMODULE: "src/code.cloudfoundry.org/winc"
      input_mapping:
        source-repo: winc-release
        module-repo: winc-master
    - task: create-release
      file: ci/bosh-cr/task.yml
      input_mapping:
        release: bumped-repo
    - task: bosh-cleanup
      file: ci/bosh-cleanup/task.yml
      params:
        BOSH_CA_CERT: {{PESTO_BOSH_CA_CERT}}
        BOSH_CLIENT: {{PESTO_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{PESTO_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{PESTO_BOSH_ENVIRONMENT}}
    - put: pesto-winc-smoke-test-deployment
      params:
        manifest: ci/winc-smoke-test-manifest/manifest.yml
        stemcells:
        - stemcell/*.tgz
        releases:
        - release-tarball/*.tgz
        cleanup: true
    - task: run-smoke-test
      file: ci/bosh-run-errand/task.yml
      params:
        BOSH_CA_CERT: {{PESTO_BOSH_CA_CERT}}
        BOSH_CLIENT: {{PESTO_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{PESTO_BOSH_CLIENT_SECRET}}
        BOSH_DEPLOYMENT: winc-smoke-test
        BOSH_ENVIRONMENT: {{PESTO_BOSH_ENVIRONMENT}}
        ERRAND_NAME: smoke-test
      ensure:
        task: delete-deployment
        file: ci/bosh-deld/task.yml
        params:
          BOSH_CA_CERT: {{PESTO_BOSH_CA_CERT}}
          BOSH_CLIENT: {{PESTO_BOSH_CLIENT}}
          BOSH_CLIENT_SECRET: {{PESTO_BOSH_CLIENT_SECRET}}
          BOSH_DEPLOYMENT: winc-smoke-test
          BOSH_ENVIRONMENT: {{PESTO_BOSH_ENVIRONMENT}}
    ensure:
      put: pesto-lock-pool
      params:
        release: pesto-lock-pool
- name: gats
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: winc-master
      passed: [test]
      trigger: true
    - get: garden-runc-release
  - task: build-winc
    file: ci/build-winc/task.yml
    tags: [windows2016]
    input_mapping:
      winc: winc-master
  - task: run-gats
    file: ci/run-gats/task.yml
    tags: [windows2016]
- name: bump-winc
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: winc-release
    - get: winc-master
      passed:
        - smoke-test
        - gats
      trigger: true
  - task: bump-submodule
    file: ci/bump-submodule/task.yml
    params:
      SUBMODULE: "src/code.cloudfoundry.org/winc"
    input_mapping:
      source-repo: winc-release
      module-repo: winc-master
  - put: winc-release
    params:
      repository: bumped-repo
      rebase: true
