resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/greenhouse-ci.git
- name: winc-develop
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry-incubator/winc.git
- name: winc-master
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry-incubator/winc.git
    private_key: {{CLOUDFOUNDRYINCUBATOR_WINC_DEPLOY_KEY}}
- name: winc-release
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry-incubator/winc-release.git
    private_key: {{CLOUDFOUNDRYINCUBATOR_WINC-RELEASE_DEPLOY_KEY}}
- name: baboon-winc-smoke-test
  type: bosh-deployment
  source:
    deployment: winc-smoke-test
    target: {{BABOON_BOSH_ENVIRONMENT}}
    client: {{BABOON_BOSH_CLIENT}}
    client_secret: {{BABOON_BOSH_CLIENT_SECRET}}
    ca_cert: {{BABOON_BOSH_CA_CERT}}
- name: stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells-release-candidates
    regexp: light-bosh-stemcell-(.*)-google-kvm-windows2016-go_agent.tgz

jobs:
- name: test
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: winc-develop
      trigger: true
    - get: winc-master
  - task: test-winc
    tags: [windows2016]
    input_mapping: { winc: winc-develop }
    file: ci/test-winc/task.yml
  - task: merge-develop-to-master
    input_mapping: { from-repo: winc-develop, to-repo: winc-master }
    file: ci/merge-repo/task.yml
    params: { FROM_BRANCH: develop }
  - put: winc-master
    params: { repository: merged-repo/to-repo }
- name: smoke-test
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: winc-release
    - get: stemcell
    - get: winc-master
      passed: [test]
      trigger: true
  - task: bump-submodule
    file: ci/bump-submodule/task.yml
    params:
      SUBMODULE: "src/code.cloudfoundry.org/winc"
    input_mapping:
      source-repo: winc-release
      module-repo: winc-master
  - task: create-release
    file: ci/bosh-cr/task.yml
    input_mapping:
      release: bumped-repo
  - task: bosh-cleanup
    file: ci/bosh-cleanup/task.yml
    params:
      BOSH_CA_CERT: {{BABOON_BOSH_CA_CERT}}
      BOSH_CLIENT: {{BABOON_BOSH_CLIENT}}
      BOSH_CLIENT_SECRET: {{BABOON_BOSH_CLIENT_SECRET}}
      BOSH_ENVIRONMENT: {{BABOON_BOSH_ENVIRONMENT}}
  - put: baboon-winc-smoke-test
    params:
      manifest: ci/winc-smoke-test-manifest/manifest.yml
      stemcells:
      - stemcell/*.tgz
      releases:
      - release-tarball/*.tgz
      cleanup: true
  - task: run-smoke-test
    file: ci/bosh-run-errand/task.yml
    params:
      BOSH_CA_CERT: {{BABOON_BOSH_CA_CERT}}
      BOSH_CLIENT: {{BABOON_BOSH_CLIENT}}
      BOSH_CLIENT_SECRET: {{BABOON_BOSH_CLIENT_SECRET}}
      BOSH_DEPLOYMENT: winc-smoke-test
      BOSH_ENVIRONMENT: {{BABOON_BOSH_ENVIRONMENT}}
      ERRAND_NAME: smoke-test
    ensure:
      task: delete-deployment
      file: ci/bosh-deld/task.yml
      params:
        BOSH_CA_CERT: {{BABOON_BOSH_CA_CERT}}
        BOSH_CLIENT: {{BABOON_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{BABOON_BOSH_CLIENT_SECRET}}
        BOSH_DEPLOYMENT: winc-smoke-test
        BOSH_ENVIRONMENT: {{BABOON_BOSH_ENVIRONMENT}}
  - put: winc-release
    params:
      repository: bumped-repo
      rebase: true
